services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cafesua
      POSTGRES_PASSWORD: tafftaff2026
      POSTGRES_DB: tafftaff
    ports:  
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: